export const colors = {
  headerBackgroundColor: '#f5717e',
  headerFontColor: '#FFFFFF',
  tabBackgroundColor: '#f5717e',
  tabIconColor: '#544e50',
  tabIconColorFocused: '#FFFFFF',
  backgroundColor: '#dad8d9',
  success: '#4CAF50',
  info: '#2196F3',
  warning: '#eaaf10',
  error: '#e64552',
  iconPressColor: '#FFFFFF',
  buttonPressedFontColor: '#FFFFFF',
  buttonPressedBackgroundColor: '#f5717e',
  ratingBackgroundColor: '#f5717e',
};
